
# Elasticsearch Config
node.name: es-vm
network.host: "0.0.0.0"
discovery.seed_hosts: ["127.0.0.1"]
cluster.initial_master_nodes: ["es-vm"]

# Kibana Config
server_port: "5601"
server_host: "0.0.0.0"
elasticsearch.hosts: ["http://127.0.0.1:9200"]
